name: Status Check Functions
on: push
jobs:
  fail:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1 # 終了ステータスを意図的にエラーにする
      - run: echo "Hello"
        if: ${{ failure() }} # failure()をつけて実行させる
